# Generated by Django 6.0.1 on 2026-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='host_spectator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='max_strikes',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='partymember',
            name='is_spectator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partymember',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
