# Generated by Django 6.0.1 on 2026-03-22 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('hackerrank', 'HackerRank')], max_length=20)),
                ('contest_name', models.CharField(max_length=255)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_before', models.IntegerField(default=0)),
                ('rating_after', models.IntegerField(default=0)),
                ('rating_change', models.IntegerField(default=0)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('held_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('hackerrank', 'HackerRank')], max_length=20)),
                ('problem_name', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=10)),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error')], max_length=5)),
                ('time_taken_mins', models.FloatField(default=0.0)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('platforms_used', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TopicStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('avg_time_mins', models.FloatField(default=0.0)),
                ('easy_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('hard_count', models.PositiveIntegerField(default=0)),
                ('strength', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak')], default='medium', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
