# Generated by Django on 2026-04-13
from django.db import migrations

def setup_dev_and_post(apps, schema_editor):
    User = apps.get_model('users', 'User')
    CommunityPost = apps.get_model('community', 'CommunityPost')
    PlatformProfile = apps.get_model('analytics', 'PlatformProfile')

    dev_email = 'siddharthgarkoti4545@gmail.com'
    # Try to find user or create
    user_qs = User.objects.filter(email=dev_email)
    if user_qs.exists():
        dev_user = user_qs.first()
    else:
        dev_user = User.objects.create(email=dev_email)

    # Force the requested structure
    dev_user.username = 'Siddharth'
    dev_user.is_admin = True
    # Give some solid base stats
    dev_user.rating = 2800 
    dev_user.streak = 99
    dev_user.save()

    # LeetCode profile Setup
    try:
        profile, created = PlatformProfile.objects.get_or_create(
            user=dev_user,
            platform='leetcode',
            defaults={'platform_username': 'SIddh_rth', 'problems_solved': 0}
        )
        if not created:
            profile.platform_username = 'SIddh_rth'
            profile.save()
    except Exception:
        pass # In case analytics model is not ready conceptually

    # Community Post Content
    body_content = (
        "Welcome to the latest update! 🚀\n\n"
        "Our team has been working hard to push out a massive stability and user-experience patch. "
        "Here are the complete patch notes for this deployment:\n\n"
        "🔹 **Authentication & Routing**\n"
        "• Login authentication pipelines have been entirely stabilized and refactored.\n"
        "• The navigation routing system is now much more robust, preventing unexpected redirects.\n"
        "• Guest Mode capability fully enabled, providing a restricted but safe exploration barrier.\n\n"
        "🔹 **AI Architecture**\n"
        "• Core AI routing engine significantly improved with intent-based context generation.\n"
        "• Advanced Multi-Modal AI Mentor deployed, enabling dynamic conversational contexts.\n"
        "• Image & Audio context support successfully connected to the parsing engine.\n\n"
        "🔹 **UX & Social Fixes**\n"
        "• Cross-platform Friend Chat logic restored and fully operational.\n"
        "• Real-time Notification engine glitches patched; caching timeouts resolved.\n"
        "• Dashboard analytics widgets upgraded with real-time UI/UX recalculation loops.\n"
        "• Challenge pool states now properly persist, preventing arbitrary refresh resets.\n"
        "• Support ticket endpoints expanded for smoother telemetry and response times.\n"
        "• ⚙️ **Performance**: Database query redundancies reduced by 30% for leaderboard views.\n"
        "• ⚙️ **Accessibility**: Enhanced keyboard navigation targets in the left-hand sidebar.\n\n"
        "Thank you all for the bug reports and feedback. Keep grinding! 🔥"
    )

    # Create the post
    post_title = "Patch Notes 1.1: Authentication, Advanced AI & UI Overhaul"
    
    # Ensure there isn't duplicate post by checking title
    if not CommunityPost.objects.filter(author=dev_user, title=post_title).exists():
        CommunityPost.objects.create(
            author=dev_user,
            post_type='update',
            title=post_title,
            body=body_content,
            tags='patch-notes,announcement,dev'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_dev_and_post),
    ]
