# Generated by Django on 2026-04-13
from django.db import migrations

def modify_post(apps, schema_editor):
    CommunityPost = apps.get_model('community', 'CommunityPost')
    User = apps.get_model('users', 'User')

    # Remove the old post
    CommunityPost.objects.filter(title="Patch Notes 1.1: Authentication, Advanced AI & UI Overhaul").delete()

    dev_user = User.objects.filter(email='siddharthgarkoti4545@gmail.com').first()
    if not dev_user:
        return
        
    title = "Patch Notes"

    body_content = (
        "This patch fundamentally introduces new AI features, improved stability, and fixes to your everyday app experience.\n\n"
        "**What's New**\n\n"
        "• **Adv AI Mentor Added:** We've integrated next-generation AI Mentoring with improved context and dynamic objective routing.\n"
        "• **Image and Audio Support:** New core engine enhancements enable robust media parsing for conversational contexts.\n"
        "• **Guest ID Available:** Added full structural support for Guest Mode, providing an isolated but safe platform exploration session.\n\n"
        "**Bug Fixes**\n\n"
        "• **Login Error Fixed:** Resolved a critical crash preventing reliable login authentication across specific browsers.\n"
        "• **Navigation System Improved:** Repaired component link logic and sidebar layouts to prevent UI collapsing and unexpected redirects.\n"
        "• **Friend Chat Fixed:** Corrected logic timeouts ensuring that live friend-chat messages dispatch and render securely.\n"
        "• **Notification Glitch Fixed:** Addressed missing dropdown logic, introducing reliable tracking and fully actionable UI handlers.\n"
        "• **Dashboard Improved:** Enhanced state calculation metrics to dynamically reflect streak and rating gains without page refreshes.\n"
        "• **Challenge Refresh Error Fixed:** Re-architected frontend data fetching limits to prevent the problem-pool from randomly resetting constraints.\n"
        "• **Support System Improved:** Upgraded ticket endpoints and backend routing logic for smoother telemetry submissions."
    )

    if not CommunityPost.objects.filter(title=title, author=dev_user).exists():
        CommunityPost.objects.create(
            author=dev_user,
            post_type='update',
            title=title,
            body=body_content,
            tags='patch-notes,announcement,dev'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20260414_0027'),
    ]

    operations = [
        migrations.RunPython(modify_post),
    ]
