# Generated by Django 6.0.1 on 2026-04-13 19:49

from django.db import migrations, models


def grant_pro_to_dev(apps, schema_editor):
    User = apps.get_model('users', 'User')
    user = User.objects.filter(email='siddharthgarkoti4545@gmail.com').first()
    if user:
        user.plan_tier = 'pro'
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_tier',
            field=models.CharField(default='basic', max_length=10),
        ),
        migrations.RunPython(grant_pro_to_dev),
    ]
